# Generated by Django 3.0.6 on 2020-06-01 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SomonTjCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.FloatField(verbose_name='price')),
                ('image', models.ImageField(upload_to='E:\\GITHUB\\PythonPro\\getproduct\\getproduct\\static/image', verbose_name='image')),
                ('current', models.CharField(max_length=3, verbose_name='current')),
                ('url', models.URLField(verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='SomonTjCategoryParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('child', models.IntegerField(verbose_name='child')),
            ],
        ),
        migrations.CreateModel(
            name='SomonTjPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.FloatField(verbose_name='price')),
                ('image', models.ImageField(upload_to='E:\\GITHUB\\PythonPro\\getproduct\\getproduct\\static/image', verbose_name='image')),
                ('current', models.CharField(max_length=3, verbose_name='current')),
                ('url', models.URLField(verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='SomonTjPhoneCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsing.SomonTjCategoryParent')),
            ],
        ),
    ]
